#!/bin/sh

RC_CONF_FILE="/etc/rc.conf.d/sing_box"

echo "===> Обновляется кэш меню OPNsense"
rm -f /var/lib/php/tmp/opnsense_menu_cache.xml /var/lib/php/tmp/opnsense_acl_cache.json
rm -f /usr/local/opnsense/service/conf/actions.d/actions_sing-box.conf
rm -f "$RC_CONF_FILE"
service configd restart >/dev/null 2>&1 || true

echo "===> Пользовательская конфигурация sing-box сохранена"
rm -f /usr/local/etc/sing-box/config.json.sample
