#!/bin/sh

echo "===> Refreshing OPNsense menu cache"
rm -f /var/lib/php/tmp/opnsense_menu_cache.xml /var/lib/php/tmp/opnsense_acl_cache.json
rm -f /usr/local/opnsense/service/conf/actions.d/actions_sing-box.conf
service configd restart >/dev/null 2>&1 || true

echo "===> Preserving user sing-box configuration"
rm -f /usr/local/etc/sing-box/config.json.sample
