#!/bin/sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
HELPER="$ROOT_DIR/src/usr/local/opnsense/scripts/OPNsense/SingBox/system_resolver.php"
TEST_ROOT="$(mktemp -d)"
INCLUDE_ROOT="$TEST_ROOT/includes"
RESOLVER_FILE="$TEST_ROOT/resolv.conf"
OUTPUT_FILE="$TEST_ROOT/output"
EXPECTED_FILE="$TEST_ROOT/expected"

cleanup()
{
    rm -rf "$TEST_ROOT"
}
trap cleanup EXIT HUP INT TERM

fail()
{
    echo "$1" >&2
    exit 1
}

mkdir -p "$INCLUDE_ROOT"
: > "$INCLUDE_ROOT/config.inc"
: > "$INCLUDE_ROOT/util.inc"

cat > "$INCLUDE_ROOT/system.inc" <<'PHP'
<?php

function system_resolvconf_generate($verbose = false)
{
    $path = getenv('SING_BOX_RESOLVER_FILE');
    $scenario = getenv('SING_BOX_RESOLVER_TEST_SCENARIO');
    $header = '# This file was automatically generated by system_resolvconf_generate()' . PHP_EOL;

    switch ($scenario) {
        case 'success':
            file_put_contents($path, $header . "domain internal\nnameserver 127.0.0.1\n");
            chmod($path, 0644);
            return;
        case 'success-ipv6':
            file_put_contents($path, $header . "nameserver fe80::1%lo0\n");
            chmod($path, 0644);
            return;
        case 'empty':
            file_put_contents($path, $header . "domain internal\n");
            chmod($path, 0644);
            return;
        case 'invalid-mode':
            file_put_contents($path, $header . "nameserver 127.0.0.1\n");
            chmod($path, 0600);
            return;
        case 'exception':
            file_put_contents($path, "damaged\n");
            chmod($path, 0644);
            throw new RuntimeException('Эмуляция ошибки генератора.');
        default:
            throw new RuntimeException('Неизвестный тестовый сценарий.');
    }
}
PHP

prepare_resolver()
{
    printf '%s\n' 'search localdomain' 'nameserver 172.19.0.2' > "$RESOLVER_FILE"
    chmod 0600 "$RESOLVER_FILE"
    cp "$RESOLVER_FILE" "$EXPECTED_FILE"
}

run_helper()
{
    scenario="$1"
    SING_BOX_RESOLVER_TEST_MODE=1 \
    SING_BOX_RESOLVER_INCLUDE_ROOT="$INCLUDE_ROOT" \
    SING_BOX_RESOLVER_FILE="$RESOLVER_FILE" \
    SING_BOX_RESOLVER_TEST_SCENARIO="$scenario" \
        php "$HELPER" > "$OUTPUT_FILE" 2>&1
}

assert_rollback()
{
    cmp -s "$EXPECTED_FILE" "$RESOLVER_FILE" \
        || fail "Исходное содержимое resolv.conf не восстановилось"
    [ "$(stat -c '%a' "$RESOLVER_FILE")" = "600" ] \
        || fail "Исходный режим resolv.conf не восстановился"
    grep -Fq 'Исходный resolv.conf восстановлен.' "$OUTPUT_FILE" \
        || fail "Результат отката resolv.conf не был подтверждён"
}

prepare_resolver
run_helper success
grep -Fq 'OK Системный resolver OPNsense восстановлен. nameserver=127.0.0.1' "$OUTPUT_FILE"
grep -Fq '# This file was automatically generated by system_resolvconf_generate()' "$RESOLVER_FILE"
grep -Fq 'nameserver 127.0.0.1' "$RESOLVER_FILE"
[ "$(stat -c '%a' "$RESOLVER_FILE")" = "644" ] \
    || fail "Штатный resolv.conf не получил режим 644"

prepare_resolver
run_helper success-ipv6
grep -Fq 'nameserver=fe80::1%lo0' "$OUTPUT_FILE"
grep -Fq 'nameserver fe80::1%lo0' "$RESOLVER_FILE"

for scenario in empty invalid-mode exception; do
    prepare_resolver
    if run_helper "$scenario"; then
        fail "Некорректный сценарий $scenario не был заблокирован"
    fi
    assert_rollback
done

echo "Восстановление системного resolver OPNsense и откат проверены"
