[start]
command:sh /usr/local/etc/rc.d/sing-box start
parameters:
type:script
message:запускается служба sing-box

[stop]
command:sh /usr/local/etc/rc.d/sing-box stop
parameters:
type:script
message:останавливается служба sing-box

[restart]
command:sh /usr/local/etc/rc.d/sing-box restart
parameters:
type:script
message:перезапускается служба sing-box
description:Перезапуск службы sing-box

[status]
command:sh /usr/local/etc/rc.d/sing-box status
parameters:
type:script_output
message:запрашивается состояние службы sing-box

[enable]
command:/usr/local/sbin/sing-box-service-config enable
parameters:
type:script_output
message:включается автозапуск sing-box

[disable]
command:/usr/local/sbin/sing-box-service-config disable
parameters:
type:script_output
message:отключается автозапуск sing-box

[enabled]
command:/usr/local/sbin/sing-box-service-config status
parameters:
type:script_output
message:запрашивается состояние автозапуска sing-box

[clearlog]
command:/usr/local/sbin/sing-box-logctl clear
parameters:
type:script_output
message:очищается журнал sing-box

[apply]
command:/usr/local/opnsense/scripts/OPNsense/SingBox/runtime_config.php apply
parameters:
type:script_output
message:применяется runtime-конфигурация sing-box
