[start]
command:sh /usr/local/etc/rc.d/sing-box start
parameters:
type:script
message:запускается служба sing-box

[stop]
command:sh /usr/local/etc/rc.d/sing-box stop
parameters:
type:script
message:останавливается служба sing-box

[restart]
command:sh /usr/local/etc/rc.d/sing-box restart
parameters:
type:script
message:перезапускается служба sing-box
description:Перезапуск службы sing-box

[status]
command:sh /usr/local/etc/rc.d/sing-box status
parameters:
type:script_output
message:запрашивается состояние службы sing-box
