#!/usr/local/bin/php
<?php

declare(strict_types=1);

const SYSTEM_RESOLVER_HEADER = '# This file was automatically generated by system_resolvconf_generate()';

function resolverFail(string $message, int $code): void
{
    fwrite(STDERR, 'ERROR ' . $message . PHP_EOL);
    exit($code);
}

function atomicResolverWrite(string $path, string $content, int $mode): bool
{
    $directory = dirname($path);
    $temporary = tempnam($directory, '.os-sing-box-resolver-');
    if ($temporary === false) {
        return false;
    }

    $written = file_put_contents($temporary, $content, LOCK_EX);
    if ($written === false || $written !== strlen($content) || !chmod($temporary, $mode)) {
        @unlink($temporary);
        return false;
    }
    if (!rename($temporary, $path)) {
        @unlink($temporary);
        return false;
    }
    return true;
}

function resolverNameservers(string $content): array
{
    $matches = [];
    preg_match_all(
        '/^[\t ]*nameserver[\t ]+([^\s#]+)[\t ]*(?:#.*)?$/m',
        $content,
        $matches
    );

    $nameservers = [];
    foreach ($matches[1] ?? [] as $address) {
        $ipAddress = $address;
        if (str_contains($address, '%')) {
            [$ipAddress, $scope] = explode('%', $address, 2);
            if ($scope === '' || preg_match('/^[A-Za-z0-9_.:-]+$/', $scope) !== 1) {
                throw new RuntimeException('Штатный resolv.conf содержал некорректный адрес DNS-сервера.');
            }
        }
        if (filter_var($ipAddress, FILTER_VALIDATE_IP) === false) {
            throw new RuntimeException('Штатный resolv.conf содержал некорректный адрес DNS-сервера.');
        }
        $nameservers[] = $address;
    }
    return array_values(array_unique($nameservers));
}

$testMode = getenv('SING_BOX_RESOLVER_TEST_MODE') === '1';
if ($testMode) {
    $includeRoot = (string)getenv('SING_BOX_RESOLVER_INCLUDE_ROOT');
    $resolverFile = (string)getenv('SING_BOX_RESOLVER_FILE');
    if ($includeRoot === '' || $resolverFile === '') {
        resolverFail('Тестовое окружение системного resolver было неполным.', 64);
    }
} else {
    $includeRoot = '/usr/local/etc/inc';
    $resolverFile = '/etc/resolv.conf';
}

foreach (['config.inc', 'util.inc', 'system.inc'] as $includeFile) {
    $includePath = $includeRoot . '/' . $includeFile;
    if (!is_readable($includePath)) {
        resolverFail('Системный компонент OPNsense был недоступен: ' . $includeFile, 69);
    }
    require_once $includePath;
}

if (!function_exists('system_resolvconf_generate')) {
    resolverFail('Штатный генератор resolver OPNsense был недоступен.', 69);
}
if (!is_file($resolverFile) || !is_readable($resolverFile)) {
    resolverFail('Исходный resolv.conf был недоступен.', 66);
}

$previousContent = file_get_contents($resolverFile);
$previousPermissions = fileperms($resolverFile);
if ($previousContent === false || $previousPermissions === false) {
    resolverFail('Не удалось сохранить исходное состояние resolv.conf.', 74);
}
$previousMode = $previousPermissions & 0777;

try {
    system_resolvconf_generate(false);

    clearstatcache(true, $resolverFile);
    $generatedContent = file_get_contents($resolverFile);
    $generatedPermissions = fileperms($resolverFile);
    if ($generatedContent === false || $generatedPermissions === false) {
        throw new RuntimeException('Сгенерированный resolv.conf был недоступен.');
    }
    if (!str_starts_with($generatedContent, SYSTEM_RESOLVER_HEADER . PHP_EOL)) {
        throw new RuntimeException('Происхождение сгенерированного resolv.conf не подтвердилось.');
    }
    if (($generatedPermissions & 0777) !== 0644) {
        throw new RuntimeException('Сгенерированный resolv.conf имел некорректный режим доступа.');
    }

    $nameservers = resolverNameservers($generatedContent);
    if ($nameservers === []) {
        throw new RuntimeException('Штатный resolv.conf не содержал DNS-серверов.');
    }

    echo 'OK Системный resolver OPNsense восстановлен. nameserver='
        . implode(',', $nameservers)
        . PHP_EOL;
    exit(0);
} catch (Throwable $error) {
    $restored = atomicResolverWrite($resolverFile, $previousContent, $previousMode);
    clearstatcache(true, $resolverFile);
    $restoredContent = $restored ? file_get_contents($resolverFile) : false;
    $restoredPermissions = $restored ? fileperms($resolverFile) : false;
    $rollbackComplete = $restoredContent === $previousContent
        && $restoredPermissions !== false
        && (($restoredPermissions & 0777) === $previousMode);

    resolverFail(
        $error->getMessage()
        . ($rollbackComplete
            ? ' Исходный resolv.conf восстановлен.'
            : ' Откат resolv.conf завершился неполностью.'),
        $rollbackComplete ? 69 : 74
    );
}
